### ISSUE TITLE
Mean and std formulas difference

### ISSUE THREAD

**Issue by tooHotSpot** [kozodoi/website#17]
First of all, thanks for an idea to calculate mean and variance of an arbitrary image dataset in this [tutorial](https://kozodoi.me/python/deep%20learning/pytorch/tutorial/2021/03/08/image-mean-std.html).

While reading the tutorial, I have noticed a difference in 2 formulas for the variance: in a header the sum of squares is divided by n, while in the end a mean squared is divided by n. Although formula in the end is wrong, code is right.

Please correct me if I am mistaken.

**Comment by kozodoi** [comment]
Hi @tooHotSpot, thanks for your comment! 

If I understand your point correctly, there is actually no error in the formula. The difference comes from the fact that the formula in the header is for **sigma** (the variance), whereas the formula in the end is for the **sum of squared mean differences**, which is only a numerator in **sigma**. 

The **sum of squared mean differences** equals **sigma** times **n**. Therefore, if you divide the formula in the end by **n**, component by component, you should get the variance formula at the top.

I hope this helps! :)

**Comment by tooHotSpot** [comment]
Sorry for late reply, please! You are right, thanks!
