### ISSUE TITLE
How to use this website as personal blog templates?

### ISSUE THREAD

**Issue by marcuswang6** [kozodoi/website#24]
Hi Nikita,
Your blog looks really nice! What should I do if I want to create my blog like yours? I turn to fastpages and find it deprecated.
Thanks in advance!

**Comment by marcuswang6** [comment]
Here is a recommended way for Chinese users to learn this blog on Mac M2 (Apple Chip):
1. clone the repo
2. install Docker Desktop (see Docker official website) 
3. install ruby with chruby (see Ruby official website)
4. in `docker-compose.yml`:
- remove watchdog service
- replace jekyll command by `bash -c "gem sources --add https://gems.ruby-china.com/ --remove https://rubygems.org/ && gem install bundler
     && chmod -R u+rwx . && jekyll serve --trace --strict_front_matter"`
- replace every `https://rubygems.org` with `https://gems.ruby-china.com`
5. in `Gemfile & Gemfile.lock`:
- replace every `https://rubygems.org` with `https://gems.ruby-china.com`
6. in `_config.yml`:
- make social_links more specific:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
- replace `remote theme: jekyll/minima` to `remote theme: jekyll/minima@1e6da7d` while 1e6da7d is the latest update tag of the repo `minima`

**Comment by kozodoi** [comment]
Hi @Waterkin,

thank you for the kind words! I apologise for the late reply, but it looks like you have already figured out how to set everything up. Many thanks for sharing the instructions here!

Best wishes,
Nikita
